#!/usr/bin/env python3
"""Build four journal figures from registered ProvFold outputs.

All panels are generated by this script. No generative image model or manual
post-processing is used.
"""

from __future__ import annotations

import csv
import hashlib
import json
import math
import os
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyArrowPatch, Rectangle
from matplotlib.ticker import MaxNLocator
from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
INPUT_DIR = HERE / "inputs"
OUTPUT_DIR = Path(os.environ.get("PROVFOLD_FIGURE_OUTPUT", HERE / "generated_run")).resolve()
sys.path.insert(0, str(HERE))

from figure_style import (  # noqa: E402
    BLUE,
    DARK,
    DOUBLE_COLUMN_IN,
    LIGHT,
    MID,
    ORANGE,
    PALE,
    PURPLE,
    TEAL,
    apply_style,
    clean_axes,
    panel_label,
)


INPUTS = {
    "benchmark_summary": INPUT_DIR / "benchmark_scenario_performance_18_scenarios.csv",
    "estimator_crosswalk": INPUT_DIR / "distinct_estimator_equivalence_classes.csv",
    "threshold_calibration": INPUT_DIR / "benchmark_support_threshold_calibration.csv",
    "public_arm_summary": INPUT_DIR / "public_arm_disease_summary.csv",
    "public_method_summary": INPUT_DIR / "public_primary_method_summary.csv",
    "public_rank_summary": INPUT_DIR / "public_rank_folding_summary.csv",
    "disbiome": INPUT_DIR / "disbiome_determinability.csv",
    "cross_arm": INPUT_DIR / "cross_arm_agreement_with_null.csv",
    "alpha_models": INPUT_DIR / "alpha_diversity_model_summary_dl_hk.csv",
    "alpha_studies": INPUT_DIR / "alpha_diversity_study_effects_and_weights.csv",
    "ah_thresholds": INPUT_DIR / "ah_threshold_surface.csv",
    "ah_omissions": INPUT_DIR / "ah_leave_one_family_out.csv",
    "hcc_grid": INPUT_DIR / "hcc_voting_unit_by_comparison_policy.csv",
    "hcc_support": INPUT_DIR / "hcc_separate_vote_support_provenance.csv",
    "hcc_summary": INPUT_DIR / "hcc_reanalysis_summary.json",
}

SCENARIOS = [
    ("reference", "Reference"),
    ("duplicate_nested_reports", "Nested\nreports"),
    ("case_control_imbalance", "Case–control\nimbalance"),
    ("high_zero_inflation", "High zero\ninflation"),
    ("too_few_families", "Too few\ngroups"),
    ("weak_effect_high_heterogeneity", "Weak /\nheterogeneous"),
    ("missing_family_metadata", "Missing group\nmetadata"),
    ("selective_sparse_reporting", "Sparse\nreporting"),
    ("ambiguous_taxonomy", "Ambiguous\ntaxonomy"),
    ("incorrect_family_merge", "Incorrect\nmerge"),
    ("incorrect_family_split", "Incorrect\nsplit"),
    ("rank_inflation", "Rank\ninflation"),
    ("comparator_leakage", "Scope-filter\ncheck"),
    ("multiple_primary_comparisons", "Multiple\npanels"),
    ("combined_stress", "Combined\nstress"),
    ("large_scale", "Large\nscale"),
    ("rank_replacement_with_lineage", "Rank replacement\n+ lineage"),
    ("rank_replacement_without_lineage", "Rank replacement\n− lineage"),
]


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def save_figure(fig: plt.Figure, stem: str, *, line_art: bool = False) -> list[Path]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for extension in ("pdf", "svg", "png"):
        path = OUTPUT_DIR / f"{stem}.{extension}"
        fig.savefig(path, dpi=600 if extension == "png" else None)
        paths.append(path)
    tif_path = OUTPUT_DIR / f"{stem}.tif"
    tif_dpi = 1200 if line_art else 600
    fig.savefig(tif_path, dpi=tif_dpi, pil_kwargs={"compression": "tiff_lzw"})
    with Image.open(tif_path) as handle:
        handle.convert("RGB").save(tif_path, format="TIFF", compression="tiff_lzw", dpi=(tif_dpi, tif_dpi))
    paths.append(tif_path)
    plt.close(fig)
    return paths


def box(ax, xy, width, height, text, *, edge=DARK, face="white", weight="normal", size=7.0) -> None:
    ax.add_patch(Rectangle(xy, width, height, facecolor=face, edgecolor=edge, linewidth=0.8))
    ax.text(xy[0] + width / 2, xy[1] + height / 2, text, ha="center", va="center",
            color=DARK, fontsize=size, fontweight=weight, linespacing=1.15)


def arrow(ax, start, end, *, colour=DARK, style="-|>") -> None:
    ax.add_patch(FancyArrowPatch(start, end, arrowstyle=style, mutation_scale=9,
                                linewidth=0.9, color=colour, shrinkA=0, shrinkB=0))


def figure_1() -> list[Path]:
    # The three panels form a single left-to-right scientific workflow.  Each
    # panel retains its original information, while restrained stage colours,
    # aligned boxes and one inter-panel arrow make the progression explicit.
    fig, axes = plt.subplots(1, 3, figsize=(DOUBLE_COLUMN_IN, 3.55), gridspec_kw={"wspace": 0.34})
    fig.subplots_adjust(left=0.035, right=0.985, top=0.88, bottom=0.055)
    stage_faces = ("#EEF4FB", "#EEF8F6", "#FCF3ED")
    stage_colours = (BLUE, TEAL, ORANGE)

    for ax, label, title, face, colour in zip(
        axes,
        ("A", "B", "C"),
        ("Analyst declarations", "Validated record path", "Registered outputs"),
        stage_faces,
        stage_colours,
    ):
        ax.set(xlim=(0, 1), ylim=(0, 1)); ax.axis("off")
        ax.add_patch(Rectangle((0.015, 0.005), 0.97, 0.965, facecolor=face,
                               edgecolor=colour, linewidth=0.8, zorder=-3))
        ax.plot([0.04, 0.96], [0.90, 0.90], color=colour, linewidth=1.4, solid_capstyle="butt")
        ax.text(0.045, 0.935, label, ha="left", va="center", fontsize=10,
                fontweight="bold", color=colour)
        ax.text(0.16, 0.935, title, ha="left", va="center", fontsize=8.3,
                fontweight="bold", color=DARK)

    ax = axes[0]
    entries = [
        (0.735, "Comparison scope"),
        (0.575, "Provenance group"),
        (0.415, "Taxon key\nand mapping"),
        (0.255, "Support and\nopposition"),
        (0.095, "Evaluability\nand omission"),
    ]
    for index, (y, label) in enumerate(entries):
        box(ax, (0.12, y), 0.76, 0.105, label, edge=BLUE, face="white", size=7.0)
        if index < len(entries) - 1:
            arrow(ax, (0.50, y - 0.006), (0.50, y - 0.045), colour=BLUE)

    ax = axes[1]
    box(ax, (0.15, 0.755), 0.70, 0.115, "Source-linked\nrecord", edge=DARK,
        face="white", weight="bold", size=6.8)
    # Continuous orthogonal split: source -> junction -> the two record states.
    ax.plot([0.50, 0.50], [0.755, 0.700], color=DARK, linewidth=0.9)
    ax.plot([0.25, 0.75], [0.700, 0.700], color=DARK, linewidth=0.9)
    arrow(ax, (0.25, 0.700), (0.25, 0.640), colour=TEAL)
    arrow(ax, (0.75, 0.700), (0.75, 0.640), colour=ORANGE)
    box(ax, (0.03, 0.495), 0.44, 0.135, "Eligible\nvote", edge=TEAL,
        face="white", weight="bold", size=6.8)
    box(ax, (0.53, 0.495), 0.44, 0.135, "Non-voting\nrecord", edge=ORANGE,
        face="white", weight="bold", size=6.8)
    arrow(ax, (0.25, 0.485), (0.25, 0.425), colour=TEAL)
    arrow(ax, (0.75, 0.485), (0.75, 0.425), colour=ORANGE)
    box(ax, (0.03, 0.270), 0.44, 0.145, "One of 10\nestimators", edge=BLUE,
        face="white", size=6.7)
    box(ax, (0.53, 0.270), 0.44, 0.145, "Abstention\nledger with\nreason", edge=ORANGE,
        face="white", size=6.0)
    # Continuous orthogonal merge into the audit output.
    ax.plot([0.25, 0.25], [0.270, 0.225], color=BLUE, linewidth=0.9)
    ax.plot([0.75, 0.75], [0.270, 0.225], color=ORANGE, linewidth=0.9)
    ax.plot([0.25, 0.75], [0.225, 0.225], color=DARK, linewidth=0.9)
    arrow(ax, (0.50, 0.225), (0.50, 0.180), colour=DARK)
    box(ax, (0.09, 0.055), 0.82, 0.115, "Record-to-result\naudit", edge=DARK,
        face="white", weight="bold", size=6.6)

    ax = axes[2]
    outputs = [
        (0.735, "Selected pairs\n+ unit counts"),
        (0.575, "Equivalence crosswalk"),
        (0.415, "Threshold\nperformance curve"),
        (0.255, "Group-omission results"),
        (0.095, "Configuration\n+ SHA-256 manifest"),
    ]
    for index, (y, label) in enumerate(outputs):
        box(ax, (0.08, y), 0.84, 0.105, label, edge=ORANGE, face="white", size=7.0)
        if index < len(outputs) - 1:
            arrow(ax, (0.50, y - 0.006), (0.50, y - 0.045), colour=ORANGE)

    # One clean arrow between each stage avoids the visually ambiguous branch
    # lines in the previous version while preserving the A -> B -> C order.
    for left_ax, right_ax, colour in zip(axes[:-1], axes[1:], (BLUE, TEAL)):
        left = left_ax.get_position()
        right = right_ax.get_position()
        fig.add_artist(FancyArrowPatch(
            (left.x1 + 0.004, (left.y0 + left.y1) / 2),
            (right.x0 - 0.004, (right.y0 + right.y1) / 2),
            transform=fig.transFigure, arrowstyle="-|>", mutation_scale=12,
            linewidth=1.2, color=colour, clip_on=False,
        ))

    return save_figure(fig, "Figure_1", line_art=True)


def figure_2() -> list[Path]:
    summaries = read_csv(INPUTS["benchmark_summary"])
    crosswalk = read_csv(INPUTS["estimator_crosswalk"])
    first_cell = {row["distinct_estimator_id"]: row["configured_cells"].split(";")[0] for row in crosswalk}
    lookup = {(r["scenario_id"], r["method"]): r for r in summaries}
    estimator_ids = ["MS1_row_unstratified", "MS2_report_unstratified", "MS3_report_comparison_votes",
                     "MS4_provenance_group_collapsed", "MS5_provenance_group_comparison_votes",
                     "MR1_row_unstratified", "MR2_report_unstratified", "MR3_report_comparison_votes",
                     "MR4_provenance_group_collapsed", "MR5_provenance_group_comparison_votes"]
    estimator_labels = ["MS1 row", "MS2 report", "MS3 report×comp.", "MS4 group", "MS5 group×comp.",
                        "MR1 row", "MR2 report", "MR3 report×comp.", "MR4 group", "MR5 group×comp."]
    matrix = np.full((10, len(SCENARIOS)), np.nan)
    for i, estimator in enumerate(estimator_ids):
        cell = first_cell[estimator]
        for j, (scenario, _) in enumerate(SCENARIOS):
            row = lookup.get((scenario, cell))
            if row:
                matrix[i, j] = float(row["f1_mean"])

    threshold_rows = [r for r in read_csv(INPUTS["threshold_calibration"]) if r["scenario_id"] == "reference"]
    threshold = defaultdict(dict)
    for row in threshold_rows:
        threshold[int(row["minimum_support"])][row["metric"]] = row

    fig = plt.figure(figsize=(DOUBLE_COLUMN_IN, 6.15))
    grid = fig.add_gridspec(2, 1, height_ratios=[1.55, 1], hspace=0.92)

    ax = fig.add_subplot(grid[0, 0])
    image = ax.imshow(matrix, vmin=0, vmax=1, cmap="viridis", aspect="auto")
    ax.set_yticks(np.arange(10), estimator_labels)
    ax.set_xticks(np.arange(len(SCENARIOS)), [label for _, label in SCENARIOS], rotation=55, ha="right", rotation_mode="anchor", fontsize=5.8)
    ax.set_title("Distinct estimators across benchmark scenarios")
    ax.set_xlabel("Benchmark scenario")
    for y in [4.5]:
        ax.axhline(y, color="white", linewidth=1.2)
    colourbar = fig.colorbar(image, ax=ax, fraction=0.024, pad=0.018)
    colourbar.set_label("Mean F1")
    panel_label(ax, "A")

    ax = fig.add_subplot(grid[1, 0])
    supports = sorted(threshold)
    for metric, label, colour, marker in [
        ("precision", "Precision", BLUE, "o"),
        ("recall", "Recall", TEAL, "s"),
        ("f1", "F1", PURPLE, "^"),
        ("false_discovery_proportion", "FDP", ORANGE, "D"),
    ]:
        means = [float(threshold[s][metric]["mean"]) for s in supports]
        ses = [float(threshold[s][metric]["monte_carlo_se"]) for s in supports]
        ax.errorbar(supports, means, yerr=ses, label=label, color=colour, marker=marker,
                    markersize=4, capsize=2, linewidth=1.1)
    ax.scatter([8, 8], [float(threshold[8]["precision"]["mean"]), float(threshold[8]["false_discovery_proportion"]["mean"])],
               facecolors="white", edgecolors=[BLUE, ORANGE], marker="o", s=24, zorder=6)
    ax.axvline(2, color=MID, linestyle="--", linewidth=0.8)
    ax.axvline(5, color=DARK, linestyle=":", linewidth=0.9)
    ax.text(2.06, 0.06, "display point", rotation=90, va="bottom", fontsize=6.3, color=DARK)
    ax.text(5.10, 0.74, "highest mean F1", ha="left", va="top", fontsize=6.3, color=DARK,
            bbox={"facecolor": "white", "edgecolor": "none", "pad": 0.8})
    ax.text(7.92, 0.58, "precision/FDP at s=8: n=90", ha="right", va="center",
            fontsize=6.5, color=DARK,
            bbox={"facecolor": "white", "edgecolor": LIGHT, "linewidth": 0.5, "pad": 1.2})
    ax.set(xlim=(0.75, 8.25), ylim=(-0.02, 1.02), xticks=supports,
           xlabel="Minimum support (8 provenance groups)", ylabel="Mean metric")
    ax.set_title("Reference-scenario support calibration")
    ax.legend(frameon=False, ncol=4, loc="upper center", bbox_to_anchor=(0.5, -0.23))
    clean_axes(ax, "y"); panel_label(ax, "B")
    fig.subplots_adjust(top=0.96, bottom=0.15, left=0.18, right=0.94)
    return save_figure(fig, "Figure_2")


def figure_3() -> list[Path]:
    arm_rows = read_csv(INPUTS["public_arm_summary"])
    method_rows = read_csv(INPUTS["public_method_summary"])
    rank_rows = read_csv(INPUTS["public_rank_summary"])
    disbiome = read_csv(INPUTS["disbiome"])[0]
    cross = read_csv(INPUTS["cross_arm"])

    totals = defaultdict(lambda: {"vote": 0, "abstain": 0})
    for row in arm_rows:
        totals[row["arm"]]["vote"] += int(row["voting_row_count"])
        totals[row["arm"]]["abstain"] += int(row["abstention_row_count"])
    totals["disbiome"] = {"vote": 0, "abstain": int(disbiome["family_indeterminate_abstention_rows"])}

    grouped = defaultdict(set)
    for row in method_rows:
        grouped[(row["arm"], row["disease_id"])].add(row["selected_pairs"])
    method_changed = sum(len(v) > 1 for v in grouped.values())
    rank_changed = sum(bool(r["added_by_lower_rank_folding"] or r["removed_after_lower_rank_folding"]) for r in rank_rows)

    fig = plt.figure(figsize=(DOUBLE_COLUMN_IN, 5.25))
    grid = fig.add_gridspec(2, 2, hspace=0.82, wspace=0.42)

    ax = fig.add_subplot(grid[0, 0])
    keys = ["rawdata", "literature", "disbiome"]
    labels = ["gutMDisorder\nraw data", "gutMDisorder\nliterature", "Disbiome\nstrict"]
    x = np.arange(3)
    vote = np.array([totals[k]["vote"] for k in keys], dtype=float)
    abstain = np.array([totals[k]["abstain"] for k in keys], dtype=float)
    total = vote + abstain
    vote_pct = 100 * vote / total
    ax.bar(x, vote_pct, color=TEAL, edgecolor=DARK, label="Eligible vote")
    ax.bar(x, 100-vote_pct, bottom=vote_pct, color=LIGHT, hatch="///", edgecolor=DARK, label="Abstention")
    for index, (eligible, abstaining) in enumerate(zip(vote, abstain)):
        ax.text(index, 103.0, f"n={int(eligible + abstaining):,}", ha="center", va="bottom",
                fontsize=7.0, color=DARK, clip_on=False)
    ax.set(xticks=x, xticklabels=labels, ylim=(0, 112), ylabel="Adapted records (%)")
    ax.set_title("Source evaluability", pad=6)
    ax.legend(frameon=False, loc="lower center", bbox_to_anchor=(0.5, 1.18),
              ncol=2, fontsize=7.0, handlelength=1.4, columnspacing=1.0)
    clean_axes(ax, "y"); panel_label(ax, "A")

    ax = fig.add_subplot(grid[0, 1])
    values = [method_changed, 16-method_changed, rank_changed, 16-rank_changed]
    labels = ["Method\nchanged", "Method\nunchanged", "Rank key\nchanged", "Rank key\nunchanged"]
    bars = ax.bar(np.arange(4), values, color=[ORANGE, LIGHT, BLUE, LIGHT], edgecolor=DARK)
    for bar, value in zip(bars, values):
        ax.text(bar.get_x()+bar.get_width()/2, value+0.25, str(value), ha="center", fontsize=7)
    ax.set(xticks=np.arange(4), xticklabels=labels, ylim=(0, 17), ylabel="Disease–arm groups")
    ax.yaxis.set_major_locator(MaxNLocator(integer=True))
    ax.set_title("Representation dependence", pad=6); clean_axes(ax, "y"); panel_label(ax, "B")

    ax = fig.add_subplot(grid[1, 0])
    disease_labels = ["Ulcerative colitis", "Crohn disease", "Parkinson disease"]
    x = np.arange(3)
    observed = np.array([float(r["observed_sign_agreement_rate"]) for r in cross])
    expected = np.array([float(r["marginal_null_expected_agreement"]) for r in cross])
    lo = observed - np.array([float(r["exact_95_ci_lower"]) for r in cross])
    hi = np.array([float(r["exact_95_ci_upper"]) for r in cross]) - observed
    ax.errorbar(x-0.08, observed, yerr=[lo, hi], fmt="o", color=BLUE, capsize=3, label="Observed (exact 95% CI)")
    ax.scatter(x+0.08, expected, marker="x", s=32, color=ORANGE, label="Marginal-independence expectation")
    ax.set(xticks=x, xticklabels=disease_labels, ylim=(0.3, 1.04), ylabel="Direction agreement")
    ax.tick_params(axis="x", rotation=18); ax.set_title("Cross-arm direction agreement", pad=6)
    ax.legend(frameon=False, loc="lower center", bbox_to_anchor=(0.5, 1.18),
              ncol=1, fontsize=7.0, handlelength=1.4)
    clean_axes(ax, "y"); panel_label(ax, "C")

    ax = fig.add_subplot(grid[1, 1])
    raw = np.array([int(r["support_2_rawdata_selected_count"]) for r in cross])
    lit = np.array([int(r["support_2_literature_selected_count"]) for r in cross])
    for i in range(3):
        ax.plot([i-0.12, i+0.12], [raw[i], lit[i]], color=LIGHT, linewidth=1.3, zorder=1)
    ax.scatter(x-0.12, raw, color=TEAL, label="Raw-data arm", zorder=3)
    ax.scatter(x+0.12, lit, color=PURPLE, label="Literature arm", zorder=3)
    for i, row in enumerate(cross):
        ax.text(i + 0.16, max(raw[i], lit[i]) - 1.4, f"J={float(row['support_2_jaccard']):.3f}",
                ha="left", va="top", fontsize=6.3)
    ax.set(xticks=x, xticklabels=disease_labels, ylim=(0, 36), ylabel="Support-2 selected pairs")
    ax.yaxis.set_major_locator(MaxNLocator(integer=True))
    ax.tick_params(axis="x", rotation=18); ax.set_title("Selected-set size and overlap", pad=6)
    ax.legend(frameon=False, loc="lower center", bbox_to_anchor=(0.5, 1.18),
              ncol=2, fontsize=7.0, handlelength=1.4, columnspacing=1.0)
    clean_axes(ax, "y"); panel_label(ax, "D")
    fig.subplots_adjust(top=0.87, bottom=0.12)
    return save_figure(fig, "Figure_3")


def selected_count(rows: list[dict[str, str]], key: str, value: str | None = None) -> int:
    pairs = set()
    for row in rows:
        if value is not None and row[key] != value:
            continue
        if row.get("signal_classification") == "retained" and row.get("selected_direction"):
            pairs.add((row.get("target_taxon") or row.get("taxon_key", ""), row["selected_direction"]))
    return len(pairs)


def figure_4() -> list[Path]:
    alpha = [r for r in read_csv(INPUTS["alpha_models"]) if r["analysis_role"] == "primary_cohort_deduplicated"]
    alpha_studies = [r for r in read_csv(INPUTS["alpha_studies"]) if r["outcome"] == "Shannon"]
    thresholds = read_csv(INPUTS["ah_thresholds"])
    omissions = read_csv(INPUTS["ah_omissions"])
    grid_rows = read_csv(INPUTS["hcc_grid"])
    hcc_support = read_csv(INPUTS["hcc_support"])
    hcc_summary = json.loads(INPUTS["hcc_summary"].read_text(encoding="utf-8"))

    fig = plt.figure(figsize=(DOUBLE_COLUMN_IN, 5.45))
    grid = fig.add_gridspec(2, 2, hspace=0.72, wspace=0.48)

    ax = fig.add_subplot(grid[0, 0])
    shannon = next(r for r in alpha if r["outcome"] == "Shannon")
    study_y = np.arange(len(alpha_studies), 0, -1)
    study_mean = np.array([float(row["smd"]) for row in alpha_studies])
    study_low = np.array([float(row["study_ci_low"]) for row in alpha_studies])
    study_high = np.array([float(row["study_ci_high"]) for row in alpha_studies])
    ax.errorbar(study_mean, study_y, xerr=[study_mean-study_low, study_high-study_mean], fmt="o", color=BLUE, ecolor=DARK, capsize=2.0, markersize=3.7)
    pooled = float(shannon["pooled_smd"])
    hk_low = float(shannon["hk_ci_low"]); hk_high = float(shannon["hk_ci_high"])
    ax.errorbar([pooled], [0], xerr=[[pooled-hk_low], [hk_high-pooled]], fmt="D", color=ORANGE, ecolor=ORANGE, capsize=2.5, markersize=4.3)
    ax.axvline(0, color=MID, linewidth=0.8, linestyle="--")
    ax.set_yticks(
        [*study_y, 0],
        [f"{row['study_label']}  {float(row['random_effect_weight_pct']):.1f}%" for row in alpha_studies]
        + ["Total 100%; DL pooled;\nsafeguarded HK 95% CI"],
    )
    ax.set_xlabel("Standardised mean difference")
    ax.set_title(f"AH Shannon diversity (I²={float(shannon['i2_pct']):.1f}%)")
    clean_axes(ax, "x"); panel_label(ax, "A")

    ax = fig.add_subplot(grid[0, 1])
    def count_setting(support: str, opposition: str) -> int:
        return len({(r["target_taxon"], r["selected_direction"]) for r in thresholds
                    if r["minimum_support"] == support and r["maximum_opposition"] == opposition
                    and r["signal_classification"] == "retained" and r["selected_direction"]})
    omission_ids = sorted({r["omitted_family_id"] for r in omissions})
    omission_values = [len({(r["target_taxon"], r["selected_direction"]) for r in omissions
                            if r["omitted_family_id"] == oid and r["signal_classification"] == "retained"
                            and r["selected_direction"]}) for oid in omission_ids]
    values = [count_setting("1", "0"), count_setting("2", "0"), *omission_values]
    labels = ["Support 1", "Support 2", "Omit\nCOH0003", "Omit\nCOH0004"]
    bars = ax.bar(np.arange(4), values, color=[TEAL, BLUE, LIGHT, LIGHT], edgecolor=DARK, hatch=["", "", "///", "///"])
    for bar, value in zip(bars, values):
        ax.text(bar.get_x()+bar.get_width()/2, value+0.35, str(value), ha="center", fontsize=7)
    ax.set(xticks=np.arange(4), xticklabels=labels, ylim=(0, 20), ylabel="Selected genus–direction pairs")
    ax.tick_params(axis="x", labelsize=6.4)
    ax.yaxis.set_major_locator(MaxNLocator(integer=True))
    ax.set_title("AH qualitative sensitivity"); clean_axes(ax, "y"); panel_label(ax, "B")

    ax = fig.add_subplot(grid[1, 0])
    units = ["report", "provenance_group"]
    policies = ["ignore", "separate_votes", "family_state"]
    lookup = {(r["voting_unit"], r["comparison_policy"]): int(r["selected_pair_count"]) for r in grid_rows}
    matrix = np.array([[lookup[(u, p)] for p in policies] for u in units])
    image = ax.imshow(matrix, cmap="Blues", vmin=0, vmax=17, aspect="auto")
    for i in range(2):
        for j in range(3):
            ax.text(j, i, str(matrix[i, j]), ha="center", va="center", fontsize=9,
                    color="white" if matrix[i, j] > 9 else DARK, fontweight="bold")
    ax.set_yticks([0, 1], ["Report", "Provenance group"])
    ax.set_xticks([0, 1, 2], ["Ignored", "Separate\npanels", "Collapsed"])
    ax.set_title("HCC configuration grid")
    for spine in ax.spines.values(): spine.set_visible(False)
    panel_label(ax, "C")

    ax = fig.add_subplot(grid[1, 1])
    single = sum(r["single_group_only"] == "True" for r in hcc_support)
    hcc_f02_only = sum(r["supporting_provenance_groups"] == "HCC-F02" for r in hcc_support)
    multi = len(hcc_support) - single
    normalised = int(hcc_summary["normalised_selected_count"])
    collapsed = 2
    ax.bar(0, single, color=ORANGE, edgecolor=DARK, label="One provenance group")
    ax.bar(0, multi, bottom=single, color=TEAL, edgecolor=DARK, label="≥2 provenance groups")
    ax.bar(1, normalised, color=PURPLE, edgecolor=DARK, label="Panels, scaled support")
    ax.bar(2, collapsed, color=BLUE, edgecolor=DARK, label="Collapsed groups")
    ax.text(0, single/2, f"{single}\n{hcc_f02_only} from\nHCC-F02", ha="center", va="center",
            color="white", fontweight="bold", fontsize=6.2, linespacing=0.95)
    ax.text(0, single+multi/2, str(multi), ha="center", va="center", color="white", fontweight="bold")
    ax.text(1, normalised+0.35, str(normalised), ha="center"); ax.text(2, collapsed+0.35, str(collapsed), ha="center")
    ax.set_xticks([0, 1, 2], ["Panels\ns = 2", "Panels\ns = 4", "Groups\ns = 2"], fontsize=6.5)
    ax.set_ylim(0, 18); ax.set_ylabel("Selected genus–direction pairs")
    ax.yaxis.set_major_locator(MaxNLocator(integer=True))
    ax.set_title("HCC support provenance"); ax.legend(frameon=False, fontsize=6.1, loc="upper right")
    clean_axes(ax, "y"); panel_label(ax, "D")
    fig.subplots_adjust(top=0.96, bottom=0.11, left=0.25, right=0.98)
    return save_figure(fig, "Figure_4")


def write_manifest(outputs: list[Path]) -> None:
    manifest = {
        "generated_by": Path(__file__).name,
        "manual_postprocessing": "none",
        "inputs": [
            {"asset": name, "path": path.name, "sha256": sha256(path)}
            for name, path in INPUTS.items()
        ],
        "outputs": [
            {"path": path.name, "size_bytes": path.stat().st_size, "sha256": sha256(path)}
            for path in outputs
        ],
    }
    (OUTPUT_DIR / "figure_provenance_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def main() -> None:
    apply_style()
    missing = [str(path) for path in INPUTS.values() if not path.is_file()]
    if missing:
        raise FileNotFoundError("Missing registered inputs: " + ", ".join(missing))
    outputs: list[Path] = []
    outputs.extend(figure_1())
    outputs.extend(figure_2())
    outputs.extend(figure_3())
    outputs.extend(figure_4())
    write_manifest(outputs)
    print(f"Generated {len(outputs)} files in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
